name: Build Cairo
on:
  push:
    tags:
      - '*'
jobs:
  Build-Release:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: sudo apt-get install mingw-w64
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ./download-cairo.sh
      - run: mkdir -p tmp/bin tmp/include tmp/lib tmp/licenses
      - run: ./pkg-config.sh
      - run: ./zlib.sh
      - run: ./libpng.sh
      - run: ./freetype.sh
      - run: ./pixman.sh
      - run: ./cairo.sh
      - run: ./pack-cairo.sh
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tmp/cairo-x86_64-w64-mingw32.tgz
          asset_name: cairo-x86_64-w64-mingw32.tgz
          tag: ${{ github.ref }}
          overwrite: true
